# Hand-written to match Django's autogenerated format (see crm/migrations/0001_initial.py)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

TENANT_AWARE_FIELDS = [
    ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
    ('updated_at', models.DateTimeField(auto_now=True)),
    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
    ('is_deleted', models.BooleanField(db_index=True, default=False)),
    ('deleted_at', models.DateTimeField(blank=True, null=True)),
    ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata for extensibility.')),
]

TENANT_AWARE_FKS = [
    ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
    ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
    ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
    ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=TENANT_AWARE_FIELDS + [
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('body_markdown', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'proposals_template'},
        ),
        migrations.CreateModel(
            name='ProposalTemplateVersion',
            fields=TENANT_AWARE_FIELDS + [
                ('version_number', models.PositiveIntegerField()),
                ('body_markdown', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='proposals.proposaltemplate')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'proposals_template_version', 'ordering': ['-version_number']},
        ),
        migrations.CreateModel(
            name='ProposalVariable',
            fields=TENANT_AWARE_FIELDS + [
                ('key', models.SlugField(help_text='Used in templates as {{key}}.', max_length=100)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('default_value', models.CharField(blank=True, max_length=500)),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'proposals_variable'},
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=TENANT_AWARE_FIELDS + [
                ('title', models.CharField(max_length=255)),
                ('body_markdown', models.TextField(blank=True, help_text='Final content after variable substitution.')),
                ('variable_values', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='crm.client')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='proposals.proposaltemplate')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'proposals_proposal'},
        ),
        migrations.CreateModel(
            name='ProposalView',
            fields=TENANT_AWARE_FIELDS + [
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='proposals.proposal')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'proposals_view', 'ordering': ['-viewed_at']},
        ),
        migrations.AddConstraint(
            model_name='proposaltemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='uniq_template_version_number'),
        ),
        migrations.AddConstraint(
            model_name='proposalvariable',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='uniq_tenant_variable_key'),
        ),
    ]
