# Hand-written to match Django's autogenerated format (see 0001_initial.py)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

TENANT_AWARE_FIELDS = [
    ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
    ('updated_at', models.DateTimeField(auto_now=True)),
    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
    ('is_deleted', models.BooleanField(db_index=True, default=False)),
    ('deleted_at', models.DateTimeField(blank=True, null=True)),
    ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata for extensibility.')),
]

TENANT_AWARE_FKS = [
    ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
    ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
    ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
    ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
]


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=TENANT_AWARE_FIELDS + [
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'files_folder'},
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='files.folder'),
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=TENANT_AWARE_FIELDS + [
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, default='#6366f1', max_length=20)),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'files_tag'},
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.folder'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='files', to='files.filetag'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=TENANT_AWARE_FIELDS + [
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='attachments/versions/')),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('file_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.fileattachment')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'files_version', 'ordering': ['-version_number']},
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('tenant', 'parent', 'name'), name='uniq_tenant_parent_folder_name'),
        ),
        migrations.AddConstraint(
            model_name='filetag',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_tenant_filetag_name'),
        ),
        migrations.AddConstraint(
            model_name='fileversion',
            constraint=models.UniqueConstraint(fields=('file_attachment', 'version_number'), name='uniq_file_version_number'),
        ),
    ]
