from django.db import models

from apps.common.models import TenantAwareModel


class Invoice(TenantAwareModel):
    class StatusChoices(models.TextChoices):
        DRAFT = "draft", "Draft"
        SENT = "sent", "Sent"
        VIEWED = "viewed", "Viewed"
        PARTIAL = "partial", "Partially Paid"
        PAID = "paid", "Paid"
        OVERDUE = "overdue", "Overdue"
        CANCELLED = "cancelled", "Cancelled"

    client = models.ForeignKey("crm.Client", on_delete=models.CASCADE, related_name="invoices")
    project = models.ForeignKey("projects.Project", on_delete=models.SET_NULL, null=True, blank=True, related_name="invoices")
    quotation = models.ForeignKey("quotations.Quotation", on_delete=models.SET_NULL, null=True, blank=True, related_name="invoices")

    invoice_number = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=20, choices=StatusChoices.choices, default=StatusChoices.DRAFT)
    issue_date = models.DateField()
    due_date = models.DateField()

    subtotal = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    discount_type = models.CharField(
        max_length=10, choices=[("flat", "Flat"), ("percent", "Percent")], default="percent"
    )
    discount_value = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    tax_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    tax_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    amount_paid = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    amount_due = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    currency = models.CharField(max_length=3, default="USD")
    notes = models.TextField(blank=True)
    paid_at = models.DateTimeField(null=True, blank=True)
    sent_at = models.DateTimeField(null=True, blank=True)

    # Recurring invoice — if set, this invoice was auto-generated by a RecurringInvoice
    recurring_invoice = models.ForeignKey(
        "invoices.RecurringInvoice", on_delete=models.SET_NULL, null=True, blank=True, related_name="generated_invoices"
    )

    class Meta:
        db_table = "invoices_invoice"
        constraints = [
            models.UniqueConstraint(fields=["tenant", "invoice_number"], name="uniq_invoice_number_per_tenant")
        ]

    def __str__(self):
        return self.invoice_number or f"Invoice #{self.id}"

    @classmethod
    def generate_invoice_number(cls, tenant):
        last = (
            cls.all_objects
            .filter(tenant=tenant, invoice_number__startswith="INV-")
            .order_by("-invoice_number")
            .values_list("invoice_number", flat=True)
            .first()
        )
        if last:
            try:
                num = int(last.split("-")[-1]) + 1
            except (ValueError, IndexError):
                num = 1
        else:
            num = 1
        return f"INV-{num:04d}"


class InvoiceLineItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name="line_items")
    description = models.CharField(max_length=255)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    unit_price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    class Meta:
        db_table = "invoices_line_item"

    def __str__(self):
        return self.description


class Payment(TenantAwareModel):
    """
    Records a payment (full or partial) against an invoice.
    Multiple payments are allowed per invoice (partial payments).
    The invoice service recalculates amount_paid / amount_due / status
    after every payment record is created or deleted.
    """

    class MethodChoices(models.TextChoices):
        BANK_TRANSFER = "bank_transfer", "Bank Transfer"
        CASH = "cash", "Cash"
        CARD = "card", "Card"
        UPI = "upi", "UPI"
        PAYPAL = "paypal", "PayPal"
        STRIPE = "stripe", "Stripe"
        OTHER = "other", "Other"

    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name="payments")
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    method = models.CharField(max_length=20, choices=MethodChoices.choices, default=MethodChoices.BANK_TRANSFER)
    paid_on = models.DateField()
    reference = models.CharField(max_length=255, blank=True, help_text="Transaction ID / cheque number / reference.")
    notes = models.TextField(blank=True)

    class Meta:
        db_table = "invoices_payment"
        ordering = ["-paid_on"]

    def __str__(self):
        return f"Payment of {self.amount} on {self.paid_on} for {self.invoice}"


class RecurringInvoice(TenantAwareModel):
    """
    Template that Celery beat uses to auto-generate Invoice instances on a schedule.
    Each generated invoice is a fresh copy with a new invoice_number.
    """

    class FrequencyChoices(models.TextChoices):
        WEEKLY = "weekly", "Weekly"
        BIWEEKLY = "biweekly", "Bi-weekly"
        MONTHLY = "monthly", "Monthly"
        QUARTERLY = "quarterly", "Quarterly"
        YEARLY = "yearly", "Yearly"

    client = models.ForeignKey("crm.Client", on_delete=models.CASCADE, related_name="recurring_invoices")
    project = models.ForeignKey("projects.Project", on_delete=models.SET_NULL, null=True, blank=True, related_name="recurring_invoices")
    frequency = models.CharField(max_length=20, choices=FrequencyChoices.choices, default=FrequencyChoices.MONTHLY)
    next_issue_date = models.DateField()
    end_date = models.DateField(null=True, blank=True, help_text="Stop generating after this date. Leave blank to run indefinitely.")
    is_active = models.BooleanField(default=True)

    # Template fields copied to each generated invoice
    tax_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    discount_type = models.CharField(max_length=10, choices=[("flat", "Flat"), ("percent", "Percent")], default="percent")
    discount_value = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    currency = models.CharField(max_length=3, default="USD")
    notes = models.TextField(blank=True)
    due_days = models.PositiveSmallIntegerField(default=30, help_text="Days after issue_date the generated invoice is due.")

    class Meta:
        db_table = "invoices_recurring"

    def __str__(self):
        return f"Recurring {self.get_frequency_display()} invoice for {self.client}"


class RecurringInvoiceLineItem(models.Model):
    """Line items template for a RecurringInvoice — copied to each generated invoice."""

    recurring_invoice = models.ForeignKey(RecurringInvoice, on_delete=models.CASCADE, related_name="line_items")
    description = models.CharField(max_length=255)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    unit_price = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    class Meta:
        db_table = "invoices_recurring_line_item"

    def __str__(self):
        return self.description
