# Generated by Django 5.1.15 on 2026-06-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="note",
            new_name="notes_note_content_7500a1_idx",
            old_name="notes_note_content_objid_idx",
        ),
    ]
