# Hand-written to match Django's autogenerated format (see crm/migrations/0001_initial.py)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

TENANT_AWARE_FIELDS = [
    ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
    ('updated_at', models.DateTimeField(auto_now=True)),
    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
    ('is_deleted', models.BooleanField(db_index=True, default=False)),
    ('deleted_at', models.DateTimeField(blank=True, null=True)),
    ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata for extensibility.')),
]

TENANT_AWARE_FKS = [
    ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
    ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
    ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
    ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('crm', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=TENANT_AWARE_FIELDS + [
                ('quotation_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('converted', 'Converted to Invoice')], default='draft', max_length=20)),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_number', models.CharField(blank=True, help_text='Client/business GSTIN, if applicable.', max_length=30)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='GST/tax %.', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='crm.client')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='proposals.proposal')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'quotations_quotation'},
        ),
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotations.quotation')),
            ],
            options={'db_table': 'quotations_line_item'},
        ),
        migrations.CreateModel(
            name='QuotationVersion',
            fields=TENANT_AWARE_FIELDS + [
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(help_text='Serialized quotation + line items at the time of this version.')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotations.quotation')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'quotations_version', 'ordering': ['-version_number']},
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('tenant', 'quotation_number'), name='uniq_quotation_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='quotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_number'), name='uniq_quotation_version_number'),
        ),
    ]
