# Hand-written to match Django's autogenerated format

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

TENANT_AWARE_FIELDS = [
    ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
    ('updated_at', models.DateTimeField(auto_now=True)),
    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
    ('is_deleted', models.BooleanField(db_index=True, default=False)),
    ('deleted_at', models.DateTimeField(blank=True, null=True)),
    ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata for extensibility.')),
]

TENANT_AWARE_FKS = [
    ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
    ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
    ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
    ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
]


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_invoice_number'),
        ('crm', '0001_initial'),
        ('projects', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── RecurringInvoice ──────────────────────────────────────────────────
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=TENANT_AWARE_FIELDS + [
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_issue_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True, help_text='Stop generating after this date. Leave blank to run indefinitely.')),
                ('is_active', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('due_days', models.PositiveSmallIntegerField(default=30, help_text='Days after issue_date the generated invoice is due.')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='crm.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoices', to='projects.project')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'invoices_recurring'},
        ),
        migrations.CreateModel(
            name='RecurringInvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recurring_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.recurringinvoice')),
            ],
            options={'db_table': 'invoices_recurring_line_item'},
        ),

        # ── New fields on Invoice ─────────────────────────────────────────────
        migrations.AddField(
            model_name='invoice',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='invoices.recurringinvoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'),
                    ('partial', 'Partially Paid'), ('paid', 'Paid'),
                    ('overdue', 'Overdue'), ('cancelled', 'Cancelled'),
                ],
                default='draft', max_length=20,
            ),
        ),

        # ── Payment ───────────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Payment',
            fields=TENANT_AWARE_FIELDS + [
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('paid_on', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Transaction ID / cheque number / reference.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'invoices_payment', 'ordering': ['-paid_on']},
        ),
    ]
