# Hand-written to match Django's autogenerated format

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

TENANT_AWARE_FIELDS = [
    ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
    ('updated_at', models.DateTimeField(auto_now=True)),
    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
    ('is_deleted', models.BooleanField(db_index=True, default=False)),
    ('deleted_at', models.DateTimeField(blank=True, null=True)),
    ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata for extensibility.')),
]

TENANT_AWARE_FKS = [
    ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
    ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
    ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
    ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('crm', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPortalAccess',
            fields=TENANT_AWARE_FIELDS + [
                ('email', models.EmailField(help_text='Login email for the portal (usually same as crm.Client.email).')),
                ('password_hash', models.CharField(blank=True, help_text='Argon2/bcrypt hash of the portal password.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invite_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to='crm.client')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'client_portal_access'},
        ),
        migrations.CreateModel(
            name='ClientPortalMessage',
            fields=TENANT_AWARE_FIELDS + [
                ('sender_type', models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], default='client', max_length=10)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='crm.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_messages', to='projects.project')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'client_portal_message', 'ordering': ['created_at']},
        ),
        migrations.AddConstraint(
            model_name='clientportalaccess',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='uniq_portal_email_per_tenant'),
        ),
    ]
