# Hand-written to match Django's autogenerated format

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

TENANT_AWARE_FIELDS = [
    ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
    ('updated_at', models.DateTimeField(auto_now=True)),
    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
    ('is_deleted', models.BooleanField(db_index=True, default=False)),
    ('deleted_at', models.DateTimeField(blank=True, null=True)),
    ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata for extensibility.')),
]

TENANT_AWARE_FKS = [
    ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
    ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
    ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
    ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('crm', '0001_initial'),
        ('projects', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=TENANT_AWARE_FIELDS + [
                ('title', models.CharField(max_length=255)),
                ('body_markdown', models.TextField(blank=True, help_text='Contract content in markdown.')),
                ('status', models.CharField(
                    choices=[
                        ('draft', 'Draft'), ('sent', 'Sent'), ('signed', 'Signed'),
                        ('active', 'Active'), ('expired', 'Expired'),
                        ('cancelled', 'Cancelled'), ('renewed', 'Renewed'),
                    ],
                    default='draft', max_length=20,
                )),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True, help_text='Leave blank for open-ended contracts.')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_reminder_days', models.PositiveSmallIntegerField(default=30, help_text='Send renewal reminder this many days before end_date.')),
                ('expiry_reminder_sent', models.BooleanField(default=False)),
                ('renewal_reminder_sent', models.BooleanField(default=False)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='contracts/signed/', help_text='Upload the signed contract file received back from the client.')),
                ('client_signature_name', models.CharField(blank=True, help_text='Name the client typed when signing (for lightweight in-app signature).', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.project')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='quotations.quotation')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'contracts_contract'},
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=TENANT_AWARE_FIELDS + [
                ('version_number', models.PositiveIntegerField()),
                ('body_markdown', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract')),
            ] + TENANT_AWARE_FKS,
            options={'db_table': 'contracts_version', 'ordering': ['-version_number']},
        ),
        migrations.AddConstraint(
            model_name='contractversion',
            constraint=models.UniqueConstraint(fields=('contract', 'version_number'), name='uniq_contract_version_number'),
        ),
    ]
